TestSuite[{
	"Unit/DefineRequiredOptions.mt"
	,
	"Unit/DeleteOptionDuplicates.mt"
	,
	"Unit/DelegateOptions.mt"
	,
	"Unit/PrependToOptions.mt"
	,
	"Unit/CopyFeatures.mt"
	,
	"Unit/SaveOptions.mt"
	,
	"Unit/RestoreOptions.mt"
	,
	"Acceptance/DelegateOptions.mt"
	,
	"Acceptance/SaveRestoreOptions/basic.mt"
	,
	"Acceptance/SaveRestoreOptions/complex.mt"
}]